dist: xenial
os: linux
language: ruby

jobs:
  include:
    # run django tests
    - language: python

      python: '3.6'

      addons:
        firefox: latest

      dist: xenial
      services:
        - xvfb
        - postgresql

      before_install:
        - wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
        - mkdir geckodriver
        - tar -xzf geckodriver-v0.26.0-linux64.tar.gz -C geckodriver
        - export PATH=$PATH:$PWD/geckodriver

      install:
        - pip install --upgrade pip
        - pip install -r requirements.txt
        - pip install -r test-requirements.txt

      before_script:
        - psql -c 'create database mercury;' -U postgres
        - python manage.py migrate
        - python manage.py collectstatic --noinput

      script:
        - black --check --diff .
        - flake8 .
        - coverage run manage.py test

      after_script:
        - coveralls
        - cat geckodriver.log

    # run the hardware tests
    - language: bash
      
      # python: '3.6'
      
      services:
          - docker
        
      before_script:
        # prepare qemu for arm emulation on x64 hardware
        - docker run --rm --privileged multiarch/qemu-user-static:register --reset
        # build image
        - docker build -t gcivil-nyu-org/spring2020-cs-gy-9223-class .
        
      script:
        # basic help world test to see if it's working
        - docker run gcivil-nyu-org/spring2020-cs-gy-9223-class grep -q "Hello, Docker!" hello.txt
        # - black --check --exclude "migrations/" hardware

            
